"""add vectors column to pages

Revision ID: 6393da0d1606
Revises: 772683aef21b
Create Date: 2025-02-24 19:12:15.409585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6393da0d1606'
down_revision = '772683aef21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vectors', postgresql.ARRAY(sa.FLOAT()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('vectors')

    # ### end Alembic commands ###
