"""update story table primary key

Revision ID: 772683aef21b
Revises: 
Create Date: 2025-02-23 20:44:41.190156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772683aef21b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['pages.entry_id'], ),
    sa.PrimaryKeyConstraint('story_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stories')
    # ### end Alembic commands ###
