"""Add personality assessments table

Revision ID: c988f2ac2484
Revises: 0653654d5da5
Create Date: 2025-02-12 22:50:49.963970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c988f2ac2484'
down_revision = '0653654d5da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_assessments',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('jungian_introversion_extraversion_rating', sa.String(length=50), nullable=True),
    sa.Column('jungian_introversion_extraversion_rationale', sa.Text(), nullable=True),
    sa.Column('jungian_sensing_intuition_rating', sa.String(length=50), nullable=True),
    sa.Column('jungian_sensing_intuition_rationale', sa.Text(), nullable=True),
    sa.Column('jungian_thinking_feeling_rating', sa.String(length=50), nullable=True),
    sa.Column('jungian_thinking_feeling_rationale', sa.Text(), nullable=True),
    sa.Column('jungian_judging_perceiving_rating', sa.String(length=50), nullable=True),
    sa.Column('jungian_judging_perceiving_rationale', sa.Text(), nullable=True),
    sa.Column('big_five_openness_rating', sa.String(length=50), nullable=True),
    sa.Column('big_five_openness_rationale', sa.Text(), nullable=True),
    sa.Column('big_five_conscientiousness_rating', sa.String(length=50), nullable=True),
    sa.Column('big_five_conscientiousness_rationale', sa.Text(), nullable=True),
    sa.Column('big_five_agreeableness_rating', sa.String(length=50), nullable=True),
    sa.Column('big_five_agreeableness_rationale', sa.Text(), nullable=True),
    sa.Column('big_five_neuroticism_rating', sa.String(length=50), nullable=True),
    sa.Column('big_five_neuroticism_rationale', sa.Text(), nullable=True),
    sa.Column('clinical_anxiety_rating', sa.String(length=50), nullable=True),
    sa.Column('clinical_anxiety_rationale', sa.Text(), nullable=True),
    sa.Column('clinical_depression_rating', sa.String(length=50), nullable=True),
    sa.Column('clinical_depression_rationale', sa.Text(), nullable=True),
    sa.Column('clinical_impulsivity_rating', sa.String(length=50), nullable=True),
    sa.Column('clinical_impulsivity_rationale', sa.Text(), nullable=True),
    sa.Column('clinical_emotional_regulation_rating', sa.String(length=50), nullable=True),
    sa.Column('clinical_emotional_regulation_rationale', sa.Text(), nullable=True),
    sa.Column('dark_triad_psychopathy_rating', sa.String(length=50), nullable=True),
    sa.Column('dark_triad_psychopathy_rationale', sa.Text(), nullable=True),
    sa.Column('dark_triad_machiavellianism_rating', sa.String(length=50), nullable=True),
    sa.Column('dark_triad_machiavellianism_rationale', sa.Text(), nullable=True),
    sa.Column('dark_triad_narcissism_rating', sa.String(length=50), nullable=True),
    sa.Column('dark_triad_narcissism_rationale', sa.Text(), nullable=True),
    sa.Column('advanced_digital_dependency_rating', sa.String(length=50), nullable=True),
    sa.Column('advanced_digital_dependency_rationale', sa.Text(), nullable=True),
    sa.Column('advanced_cognitive_rigidity_rating', sa.String(length=50), nullable=True),
    sa.Column('advanced_cognitive_rigidity_rationale', sa.Text(), nullable=True),
    sa.Column('advanced_social_anxiety_rating', sa.String(length=50), nullable=True),
    sa.Column('advanced_social_anxiety_rationale', sa.Text(), nullable=True),
    sa.Column('advanced_environmental_sensitivity_rating', sa.String(length=50), nullable=True),
    sa.Column('advanced_environmental_sensitivity_rationale', sa.Text(), nullable=True),
    sa.Column('positive_resilience_rating', sa.String(length=50), nullable=True),
    sa.Column('positive_resilience_rationale', sa.Text(), nullable=True),
    sa.Column('positive_self_efficacy_rating', sa.String(length=50), nullable=True),
    sa.Column('positive_self_efficacy_rationale', sa.Text(), nullable=True),
    sa.Column('positive_coping_skills_rating', sa.String(length=50), nullable=True),
    sa.Column('positive_coping_skills_rationale', sa.Text(), nullable=True),
    sa.Column('positive_growth_mindset_rating', sa.String(length=50), nullable=True),
    sa.Column('positive_growth_mindset_rationale', sa.Text(), nullable=True),
    sa.Column('positive_emotional_intelligence_rating', sa.String(length=50), nullable=True),
    sa.Column('positive_emotional_intelligence_rationale', sa.Text(), nullable=True),
    sa.Column('positive_optimism_rating', sa.String(length=50), nullable=True),
    sa.Column('positive_optimism_rationale', sa.Text(), nullable=True),
    sa.Column('interpersonal_attachment_style_rating', sa.String(length=50), nullable=True),
    sa.Column('interpersonal_attachment_style_rationale', sa.Text(), nullable=True),
    sa.Column('interpersonal_social_interaction_rating', sa.String(length=50), nullable=True),
    sa.Column('interpersonal_social_interaction_rationale', sa.Text(), nullable=True),
    sa.Column('interpersonal_empathy_type_rating', sa.String(length=50), nullable=True),
    sa.Column('interpersonal_empathy_type_rationale', sa.Text(), nullable=True),
    sa.Column('interpersonal_social_hierarchy_rating', sa.String(length=50), nullable=True),
    sa.Column('interpersonal_social_hierarchy_rationale', sa.Text(), nullable=True),
    sa.Column('interpersonal_dark_rating', sa.String(length=50), nullable=True),
    sa.Column('interpersonal_dark_rationale', sa.Text(), nullable=True),
    sa.Column('interpersonal_prosocial_traits_rating', sa.String(length=50), nullable=True),
    sa.Column('interpersonal_prosocial_traits_rationale', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personality_assessments')
    # ### end Alembic commands ###
